name: PR Test
 
on:
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./kupica

    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.working-directory }}
        run: chmod +x ./gradlew

      - name: Copy credential info
        working-directory: ${{ env.working-directory }}
        run: ./gradlew copyCredential
 
      - name: Test with Gradle
        working-directory: ${{ env.working-directory }}
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        working-directory: ${{ env.working-directory }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
