name: PR Test
 
on:
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      
      
      - name: Move to source root directory
        run: cd ./kupica
      
      - name: Temp ls
        run: ls -a

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
 
      - name: Test with Gradle
        run: ./gradlew --info test

