spring:
  application:
    name: kupica
  profiles:
    include:
      - database
      - credential
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
server:
  shutdown: graceful
